apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lenovo
  name: lcp-ming-minio
spec:
  selector:
    matchLabels:
      app: lcp-ming-minio
  replicas: 1
  template:
    metadata:
      labels:
        app: lcp-ming-minio
    spec:
      containers:
        - name: lcp-ming-minio
          image: minio/minio:RELEASE.2020-11-19T23-48-16Z
          args:
            - server
            - /data
          ports:
            - containerPort: 9000
          env:
            - name: MINIO_ACCESS_KEY
              value: "testadmin"
            - name: MINIO_SECRET_KEY
              value: "testadmin"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data
              name: minio-persistent-storage
      volumes:
        - name: minio-persistent-storage
          persistentVolumeClaim:
            claimName: lcp-ming-minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  namespace: lenovo
  name: lcp-ming-minio-service
spec:
  selector:
    app: lcp-ming-minio
  ports:
    - protocol: TCP
      port: 9000
      nodePort: 31900
  type: NodePort
